version: '3'

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - /mnt/volume_nyc1_03/postgres_data:/var/lib/postgresql/data
    env_file:
      - config.env

  redis:
    image: redis:5.0.5-alpine
    restart: always
    env_file:
      - config.env

  api:
    image: jhackshaw/termninja-api
    restart: always
    ports:
      - 443:3000
    depends_on:
      - postgres
      - redis
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    env_file:
      - config.env

  games:
    image: jhackshaw/termninja-games
    restart: always
    ports:
      - 3333:3000
    depends_on:
      - postgres
      - redis
      - api
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    env_file:
      - config.env
